OnlineActivityMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineActivityMVC.Models;
using System.Diagnostics;
using Business.Abstract;
using Entities.Dtos.Concrete.ActivityDtos;
using Entities.Dtos.Concrete.CategoryDtos;
using Entities.Enums;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;

namespace OnlineActivityMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IActivityService _activityService;


        public HomeController(ILogger<HomeController> logger, IActivityService activityService)
        {
            _activityService = activityService;
        }


        //[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme, Roles = "USER")]
        [HttpGet]
        public IActionResult Index([FromQuery] ActivityFilterDto activityFilterDto)
        {
            activityFilterDto.ActivityStatus = ActivityStatus.Approved;
            var activityResult = _activityService.GetList(activityFilterDto);
            var activityViewModel = new ActivityViewModel
            {
                Activities = activityResult.Data
            };
            return View(activityViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

OnlineActivityMVC/ViewComponents/DashboardFilterViewComponent.cs
using Business.Abstract;
using Entities.Dtos.Concrete.CategoryDtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using OnlineActivityMVC.Models;

namespace OnlineActivityMVC.ViewComponents;

public class DashboardFilterViewComponent : ViewComponent
{
    private readonly ICategoryService _categoryService;
    private readonly ICityService _cityService;

    public DashboardFilterViewComponent(ICategoryService categoryService, ICityService cityService)
    {
        _categoryService = categoryService;
        _cityService = cityService;
    }

    public ViewViewComponentResult Invoke()
    {
        var categories = _categoryService.GetList(new CategoryFilterDto());
        var cities = _cityService.GetList();
        var model = new DashboardFilterViewModel
        {
            Categories = categories.Data,
            Cities = cities.Data
        };
        return View(model);
    }
}

OnlineActivityMVC/Views/Home/Index.cshtml
@model ActivityViewModel

@{
    ViewData["Title"] = "Home Page";
}

<!--begin::Container-->
<div class="container">
    <!--begin::Page Layout-->
    <div class="d-flex flex-row">
        <!--begin::Aside-->
        <div class="flex-column offcanvas-mobile w-300px w-xl-325px" id="kt_profile_aside">
            <!--begin::Forms Widget 15-->
            <div class="card card-custom gutter-b">
                <!--begin::Body-->
                <div class="card-body">
                    @await Component.InvokeAsync("DashboardFilter")
                </div>
                <!--end::Body-->
            </div>
            <!--end::Forms Widget 15-->
        </div>
        <!--end::Aside-->
        <!--begin::Layout-->
        <div class="flex-row-fluid ml-lg-8">
            <!--begin::Card-->
            <div class="card card-custom card-stretch gutter-b">
                <div class="card-body">
                    <!--begin::Section-->
                    <div class="row">
                        <!--begin::Product-->
                        @foreach (var activity in @Model.Activities)
                        {
                            <div class="col-md-4 col-lg-12 col-xxl-4">
                                <div class="card card-custom gutter-b card-stretch">

                                    <a href="@Url.Action("Index", "Activity", new {Id = activity.Id})">
                                        <div class="card-body d-flex flex-column rounded bg-light text-center">
                                            <div class="text-center rounded mb-7">
                                                <img src="https://picsum.photos/200" class="mw-100 w-200px"/>
                                            </div>
                                            <div class="mb-4">
                                                <h4 class="font-size-h6">
                                                    <div class="text-dark-75 font-weight-bolder">@activity.Name[..Math.Min(activity.Name.Length, 25)]</div>
                                                </h4>
                                                <div class="font-size-h5 text-muted font-weight-bolder">@activity.Category.Name</div>
                                            </div>
                                            <span class="label label-inline label-lg label-secondary btn-sm font-weight-bold">@activity.City.Name</span>
                                            @if (@activity.IsTicket)
                                            {
                                                <span class="label label-inline label-lg label-light-primary btn-sm font-weight-bold mt-4">@activity.Price ₺</span>
                                            }
                                            else
                                            {
                                                <span class="label label-inline label-lg label-light-primary btn-sm font-weight-bold mt-4">Ücretsiz</span>
                                            }
                                        </div>
                                    </a>

                                </div>
                            </div>
                        }
                        <!--end::Product-->
                    </div>
                    <!--end::Section-->
                </div>
            </div>
            <!--end::Card-->
        </div>
        <!--end::Layout-->
    </div>
    <!--end::Page Layout-->
</div>
<!--end::Container-->